version: 1
applications:
  - backend:
      phases:
        preBuild:
          commands:
            - echo "Installing Python dependencies..."
            - python -m pip install --upgrade pip
            - pip install -r requirements.txt
        build:
          commands:
            - echo "Building FastAPI application..."
            # Copy all necessary files to output directory
            - mkdir -p build
            - cp -r api build/
            - cp -r core build/
            - cp -r static build/
            - cp requirements.txt build/
            # Create startup script
            - |
              cat > build/start.sh << 'EOF'
              #!/bin/bash
              uvicorn api.main:app --host 0.0.0.0 --port 8000
              EOF
            - chmod +x build/start.sh
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
    appRoot: .
    frontend:
      phases:
        build:
          commands:
            - echo "Static files will be served by FastAPI"
      artifacts:
        baseDirectory: static
        files:
          - '**/*'