#!/bin/bash

echo "🔄 Updating Frontend API Endpoints"
echo "=================================="
echo ""
echo "Your frontend at saigbox.com appears to be a Next.js application that needs to be rebuilt."
echo ""
echo "The frontend is still using the old API endpoint:"
echo "  ❌ http://3.233.250.55:8000"
echo ""
echo "It needs to be updated to use:"
echo "  ✅ https://api.saigbox.com"
echo ""
echo "STEPS TO FIX:"
echo "============="
echo ""
echo "1. FIND YOUR FRONTEND CODE:"
echo "   - Look for your Next.js/React frontend repository"
echo "   - It's likely in a separate repository from this backend"
echo ""
echo "2. UPDATE THE API ENDPOINT:"
echo "   Search for files containing '3.233.250.55:8000' and replace with 'api.saigbox.com'"
echo "   Common locations:"
echo "   - .env or .env.production"
echo "   - config.js or constants.js" 
echo "   - pages/login.js or components/Login.jsx"
echo ""
echo "3. UPDATE PROTOCOL:"
echo "   Change 'http://' to 'https://'"
echo ""
echo "4. REBUILD AND DEPLOY:"
echo "   - npm run build"
echo "   - Deploy to your hosting service (Vercel, Netlify, AWS Amplify, etc.)"
echo ""
echo "TEMPORARY WORKAROUND:"
echo "===================="
echo "While you update the frontend, you can test the OAuth flow directly:"
echo ""
echo "1. Visit: https://api.saigbox.com/docs"
echo "2. Try the /api/auth/google/url endpoint"
echo "3. Or test directly: https://api.saigbox.com/api/auth/google/url"
echo ""
echo "The backend API is fully functional with HTTPS!"
echo ""